### ISSUE TITLE
Document trans_battery_flag

### ISSUE THREAD

**Issue by michael-slx** [weatherlink/weatherlink-live-local-api#10]
It would be great to have some documentation added regarding the `trans_battery_flag` field in the API responses.

I obviously assume it has to do something with the status of the transmitter's battery, but the (excellent) documentation lacks any information on what values this field can have, etc..The only thing it says is: `transmitter battery status flag **(no unit)**`

**Comment by mcrossley** [comment]
I believe it is 0/1 value.
0=OK, 1=Low

**Comment by devanlai** [comment]
Hi @michael-slx, I've updated the documentation to define the values for the `trans_battery_flag` field. As @mcrossley said, a value of 1 indicates the battery is low, while a value of 0 indicates the battery is okay.

**Comment by michael-slx** [comment]
I had figured as much, in any case, thanks for the extremely quick response.
