### ISSUE TITLE
malformed http response header

### ISSUE THREAD

**Issue by sis6326r** [weatherlink/weatherlink-live-local-api#12]
Response contains header "ontent-type: application/json"
Should be "content-type: application/json"

full raw response example below (did masked):

ontent-type: application/json

{"data":{"did":"XXXXXXXXXXXX","ts":1663941169,"conditions":[{"lsid":551202,"data_structure_type":1,"txid":2,"temp": 55.3,"hum":67.7,"dew_point": 44.8,"wet_bulb": 48.9,"heat_index": 54.3,"wind_chill": 55.3,"thw_index": 54.3,"thsw_index":null,"wind_speed_last":0.00,"wind_dir_last":0,"wind_speed_avg_last_1_min":1.00,"wind_dir_scalar_avg_last_1_min":258,"wind_speed_avg_last_2_min":0.81,"wind_dir_scalar_avg_last_2_min":258,"wind_speed_hi_last_2_min":2.00,"wind_dir_at_hi_speed_last_2_min":257,"wind_speed_avg_last_10_min":1.50,"wind_dir_scalar_avg_last_10_min":256,"wind_speed_hi_last_10_min":5.00,"wind_dir_at_hi_speed_last_10_min":257,"rain_size":2,"rain_rate_last":0,"rain_rate_hi":0,"rainfall_last_15_min":0,"rain_rate_hi_last_15_min":0,"rainfall_last_60_min":0,"rainfall_last_24_hr":0,"rain_storm":null,"rain_storm_start_at":null,"solar_rad":null,"uv_index":null,"rx_state":0,"trans_battery_flag":0,"rainfall_daily":0,"rainfall_monthly":0,"rainfall_year":0,"rain_storm_last":null,"rain_storm_last_start_at":null,"rain_storm_last_end_at":null},{"lsid":551200,"data_structure_type":4,"temp_in": 77.0,"hum_in":43.6,"dew_point_in": 53.2,"heat_index_in": 76.4},{"lsid":551199,"data_structure_type":3,"bar_sea_level":30.098,"bar_trend":null,"bar_absolute":29.320}]},"error":null}

**Comment by devanlai** [comment]
Hi @sis6326r,

Thank you for reporting this. I haven't been able to reproduce this issue, and I can't see an obvious root cause. It would be a huge help if you could collect a [Wireshark](https://www.wireshark.org/) packet capture when this happens again. You can email it to me privately at `devan.lai` [at] `aem.eco`.

**Comment by sis6326r** [comment]
Hi @devanlai,
I think I found the root cause of the problem. Response where I found malformed header was from Postman. Main reason that I stared to analyze response with Postman was Weatherlink library for home assistant (written in python). This library has problem when parsing response from WeatherlinkLive API. Binary analysis  of the packets led me to cause of the problem. Response header consists of two lines - one is "HTTP/1.1 200 OK" and the second is "content-type: application/json", but the separator between those two lines is not [RFC compilant](https://www.rfc-editor.org/rfc/rfc7230#section-3). It consists of 0xA 0x0D chars but should be 0xD 0xA. Furthermore http header separator is also not RFC compliant (0xA 0xA - should be double CRLF). It would be great if you could fix it :)

Regards
Rafal

**Comment by devanlai** [comment]
Hi @sis6326r,
Thanks for following up. You must have a WeatherLink Live from the first batch of units we built. We fixed the header line ending issue within a couple of months of the initial release.

Please contact our tech support at `support@davisinstruments.com` to arrange for a remote firmware update. Including "WLL Firmware Update" in the email subject will help expedite your request.
