### ISSUE TITLE
Daily rain reset at midnight

### ISSUE THREAD

**Issue by grebleem** [weatherlink/weatherlink-live-local-api#4]
To detect the rainfall in a weewx driver, I use the 'rainfall_daily' to detect rain. This value should be reset to zero at local midnight. However sometimes this is not happening. This package is from 00:00:01 but the rainfall_daily is still set at 11.

Any idea why this is happening?

{'did': '001D0A71154A', 'ts': 1595973601, 'conditions': [{'lsid': 325579, 'data_structure_type': 1, 'txid': 2, 'wind_speed_last': 4.0, 'wind_dir_last': 236, 'rain_size': 2, 'rain_rate_last': 0, 'rain_15_min': 0, 'rain_60_min': 0, 'rain_24_hr': 11, 'rain_storm': 11, 'rain_storm_start_at': 1595910301, 'rainfall_daily': 11, 'rainfall_monthly': 231, 'rainfall_year': 2118, 'wind_speed_hi_last_10_min': 7.0, 'wind_dir_at_hi_speed_last_10_min': 226}, {'lsid': 325580, 'data_structure_type': 1, 'txid': 3, 'wind_speed_last': None, 'wind_dir_last': None, 'rain_size': 1, 'rain_rate_last': 0, 'rain_15_min': 0, 'rain_60_min': 0, 'rain_24_hr': 0, 'rain_storm': None, 'rain_storm_start_at': None, 'rainfall_daily': 0, 'rainfall_monthly': 0, 'rainfall_year': 0, 'wind_speed_hi_last_10_min': None, 'wind_dir_at_hi_speed_last_10_min': None}]}

**Comment by devanlai** [comment]
Hi @grebleem,

Any processing that's tied to the wall clock time such as the midnight reset is only processed every two seconds. To allow for some processing delay (a lot of work happens right on the hour), we would recommend waiting at least five seconds after midnight before the checking to see if the midnight reset has been processed.

Please let us know if you still see issues with the daily rain even after waiting five seconds.
Thanks,
-Devan.

**Comment by grebleem** [comment]
Hi Devan,

Thank you for the quick response. That makes a lot of sense! I will not bother the wll around midnight for a few seconds ;-) 
If there is something else I will open another ticket.

Cheers,
Bastiaan
