### ISSUE TITLE
2nd Feature request - Archive data in WLL

### ISSUE THREAD

**Issue by Drealine** [weatherlink/weatherlink-live-local-api#6]
I've created a second issue.
I doesn't have an answer from my previous feature.
Please hear us Davis support. 

@devanlai @gitter-badger @jeremywall-davis @lavanyan-davisnet

**Comment by Bug-Storm** [comment]
i Waiting the answer :)

**Comment by devanlai** [comment]
Hi @Drealine,

While we value your feedback, this repository's issue tracker is not the appropriate channel to request whole new features or inquire into our internal development schedule. Issues in this repository should be limited to:
1. Reporting defects in our local API functionality or documentation.
2. Asking questions about how to use the local API
3. Suggesting minor enhancements to the API that do not rise to the level of requiring product management.

Your suggestion from #2 has been forwarded onto our internal support and product development team. If you have any further feature requests or feedback, please reach out to us at support@davisinstruments.com.
